# Project Identification
sonar.projectKey=suryayenumula0_ai-resume
sonar.organization=ai-resume-v1

# Source Folders
# If your code is in the root, just use "sonar.sources=."
# If you have specific folders:
sonar.sources=backend,frontend
sonar.sourceEncoding=UTF-8

# Exclude heavy folders and test files from source analysis
sonar.exclusions=**/node_modules/**, **/.venv/**, **/migrations/**, **/*.test.js, **/*.spec.js

# Coverage paths (Adjust based on where your tests output reports)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info