# Generated by Django 6.0.2 on 2026-02-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('extracted_text', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255)),
                ('ai_score', models.IntegerField(default=0)),
            ],
        ),
    ]
