# Generated by Django 6.0.2 on 2026-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='extracted_text',
            new_name='raw_content',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='candidate_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='filename',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(default=5, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
