# Generated by Django 6.0.2 on 2026-04-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
