# Generated by Django 6.0.2 on 2026-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_rename_extracted_text_resume_raw_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='raw_content',
            new_name='extracted_text',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='resume_file',
        ),
        migrations.AddField(
            model_name='resume',
            name='jd_file',
            field=models.FileField(null=True, upload_to='jds/'),
        ),
    ]
