# Generated by Django 6.0.2 on 2026-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_resumebatch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience_score',
            field=models.IntegerField(default=0),
        ),
    ]
