# Generated by Django 6.0.2 on 2026-03-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_rename_raw_content_resume_extracted_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
