# Generated by Django 6.0.4 on 2026-04-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_resume_experience_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumebatch',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
