# Generated by Django 6.0.2 on 2026-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_alter_resume_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
        migrations.AlterField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
