# Generated by Django 6.0.2 on 2026-03-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0005_remove_resume_title_alter_resume_extracted_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='extracted_text',
            new_name='extracted_text1',
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
