# Generated by Django 6.0.2 on 2026-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0006_rename_extracted_text_resume_extracted_text1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='jds/'),
        ),
    ]
