# Generated by Django 6.0.2 on 2026-03-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0007_alter_resume_jd_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='analysis_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
