# Generated by Django 6.0.2 on 2026-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0009_resumebatch_resume_experience_years_resume_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='score',
            new_name='ai_score',
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='confidence_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='manual_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
